- name: Install UFW if not present
  apt:
    name: ufw
    state: present
    update_cache: yes

- name: Allow SSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow HTTP
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow HTTPS
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Set default UFW policy to allow
  ufw:
    direction: incoming
    policy: allow

- name: Enable UFW
  ufw:
    state: enabled

- name: Verify UFW status and rules
  shell: ufw status verbose
  register: ufw_status

- name: Show UFW status output
  debug:
    var: ufw_status.stdout
